#!/bin/bash
export CUDA_VISIBLE_DEVICES=1

CK_EG_SOLVER=${CK_ENV_EG_BIN}
# to fix 
CK_EG_SOLVER_NAME=egsolver


CK_EG_ALG="--eg "
#VARIABLE USED
echo "##########################################"
echo "Dataset PATH: "$CK_EG_DATASET_PATH
echo "Output PATH: "$CK_EG_DATASET_PATH_OUTPUT
echo "EGSolver BIN PATH: "$CK_EG_SOLVER
echo "Version: "${CK_EG_VERSION}
echo "Small bucket: "${CK_EG_LW} 
echo "Large bucket: "${CK_EG_UP} 
echo "Degree bucket": ${CK_EG_OUTDEGREE}
echo "Algorithm: "${CK_EG_ALG}
echo "Iterations: "${CK_EG_ITERATIONS} 
echo "THREAD BLOCK: "${CK_EG_GPU_TB}
echo "Extra Options: "${CK_EXTRA_OPT}
echo "TIMEOUT: "${CK_EG_TIMEOUT}
echo "##########################################"




if [ -z "$CK_EG_DATASET_PATH" ]
then
      echo "ERROR!!!! CK_EG_DATASET_PATH is not defined"
      exit 0
fi 

if [ -z "$CK_EG_DATASET_PATH_OUTPUT" ]
then
      echo "WARNING!!!! CK_EG_DATASET_PATH_OUTPUT is not defined"
      echo "Creating "`pwd`"/output"
      CK_EG_DATASET_PATH_OUTPUT=`pwd`/tmp-output-${CK_EG_SOLVER_NAME}-bucket-${CK_EG_OUTDEGREE}-${CK_EG_LW}-${CK_EG_UP}-${CK_ENV_DATASET_EGSOLVER_DATASET_NAME}
      
      mkdir -p $CK_EG_DATASET_PATH_OUTPUT
      echo $CK_EG_DATASET_PATH_OUTPUT
fi 


start=`date`
for istanza in $CK_EG_DATASET_PATH/*.*.gz ; do \
tem=`basename $istanza .gz`
sol=`basename $tem`
echo ;
date ;
echo "$tem --> $sol.sol" ;
$CK_EG_SOLVER  --input $istanza  --eg ${CK_EG_ITERATIONS}  --gpu --timeout ${CK_EG_TIMEOUT} --outdegree ${CK_EG_OUTDEGREE} ${CK_EG_LW} ${CK_EG_UP} --tb ${CK_EG_GPU_TB} ${CK_EXTRA_OPT} > $CK_EG_DATASET_PATH_OUTPUT/${sol}.sol  2>&1

soloutput=$CK_EG_DATASET_PATH_OUTPUT/${sol}.sol



mytime=`grep "Solving time:" $soloutput | cut -d " " -f3`
usec=`grep "Nodes per second:" $soloutput | cut -d " " -f4`
avgdeg=`grep "Avg out-degree" $soloutput | cut -d " " -f3`
echo "Printing entry in dataset results"
echo $tem "N/s": $usec
echo $tem $avgdeg $mytime $usec >> $CK_EG_DATASET_PATH_OUTPUT/dataset-results.txt 2>&1

echo "--------------------------";
 
echo "--------------------------";
sleep 5 ;
done
echo "==========================";
end=`date`
# copy configuration of the experiment
echo "Start Experiment: "$start > $CK_EG_DATASET_PATH_OUTPUT/experiment.txt

echo "Dataset PATH: "$CK_EG_DATASET_PATH
echo "Output PATH: "$CK_EG_DATASET_PATH_OUTPUT
echo "EGSolver BIN PATH: "$CK_EG_SOLVER
echo "Version: "${CK_EG_VERSION}
echo "Small bucket: "${CK_EG_LW} 
echo "Large bucket: "${CK_EG_UP} 
echo "Degree bucket": ${CK_EG_OUTDEGREE}
echo "Algorithm: "${CK_EG_ALG}
echo "Iterations: "${CK_EG_ITERATIONS} 
echo "THREAD BLOCK: "${CK_EG_GPU_TB}
echo "Extra Options: "${CK_EXTRA_OPT}
echo "TIMEOUT: "${CK_EG_TIMEOUT}


echo "End Experiment: "$end >> $CK_EG_DATASET_PATH_OUTPUT/experiment.txt
echo "##########################################"

export CK_EG_DATASET_PATH_OUTPUT
